#!/bin/bash

VERSION=5.0.1

/usr/bin/rm plg_authentication_emailx.zip
/usr/bin/rm -rf package/packages
/usr/bin/mkdir -p package/packages
/usr/bin/mkdir -p releases/$VERSION

/usr/bin/cp pkg_emailx.xml package

cd plugin && zip -r ../package/packages/plg_auth_emailx-$VERSION.zip . && cd -
cd system && zip -r ../package/packages/plg_system_emailx-$VERSION.zip . && cd -

cd package && zip -r ../plg_authentication_emailx.zip . && cd -
/usr/bin/cp plg_authentication_emailx.zip releases/$VERSION/plg_authentication_emailx-$VERSION.zip


sha256sum --tag releases/$VERSION/plg_authentication_emailx-$VERSION.zip
sha384sum --tag releases/$VERSION/plg_authentication_emailx-$VERSION.zip
sha512sum --tag releases/$VERSION/plg_authentication_emailx-$VERSION.zip
